# Generated by Django 4.1.7 on 2023-03-03 18:44

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserAccountManager()),
            ],
        ),
    ]
